### ISSUE TITLE
Table: 当Column同时设置fixed，verticalAlign，rowSpan时元素会被遮挡

### ISSUE THREAD

**Issue by zhouguoqing917** [rsuite/rsuite-table#394]
### Versions  
``
| package        | version |
| -------------- | ------- |
| `react`        | `18.0.2` |
| `rsuite-table` | `5.8.2` |

Table: 当Column同时设置fixed，verticalAlign，rowSpan时元素会被遮挡；
同样的问题再rsuite table也出现 https://github.com/rsuite/rsuite/issues/2527
 [demo](https://user-images.githubusercontent.com/37280505/171994017-191c0b19-c289-46df-910c-3dcc3f8c979f.png)

**Comment by simonguo** [comment]
目前还没找到比较好的解决方式，你如果有什么修改方案可以提。

**Comment by lee-chance** [comment]
```css
.rs-table-cell-group-fixed-left {
  background-color: transparent;
}
```
I'm using this hack temporarily.
