### ISSUE TITLE
单独使用表格组件样式部分不生效，如边框属性，用rsuite/dist/rsuite.min.css就生效

### ISSUE THREAD

**Issue by perfectyang** [rsuite/rsuite-table#406]
### Versions

| package        | version |
| -------------- | ------- |
| `react`        | `18.0.0` |
| `rsuite-table` | `5.9.0` |

### What is the expected behavior?
<img width="803" alt="image" src="https://user-images.githubusercontent.com/8724828/221330476-50835070-e8b9-40ca-a8d3-93cc4fd5d639.png">

### What is the current behavior?
<img width="824" alt="image" src="https://user-images.githubusercontent.com/8724828/221330444-ae539478-77eb-488b-898a-999316a1c2cb.png">
<img width="807" alt="image" src="https://user-images.githubusercontent.com/8724828/221330563-8a1d71d1-87e3-4796-9d9a-0d0826e1a72d.png">

**Comment by simonguo** [comment]
@perfectyang  你好！
你可以临时通过以下添加 CSS 方式修复

```css
* {
  box-sizing: border-box;
}
```
或者

```css
.rs-table-cell,
.rs-table-cell-content {
  box-sizing: border-box;
}
```
