### ISSUE TITLE
请示增加用户判断是否需要高亮当前行的功能

### ISSUE THREAD

**Issue by fallenleavesguy** [rsuite/rsuite-table#415]
### What problem does this feature solve?

请求增加功能，希望hover可以跳过某些行，有些行用来做表内标题，不希望他高亮

### What does the proposed API look like?

原来hover是boolean, 可以增加支持function类型，函数签名像rowHeight属性一样，用户自行判断是否高亮
增加onHover属性也可以

# 谢谢作者

**Comment by simonguo** [comment]
你可以通过 `rowClassName` 为你需要显示高亮的行添加 className,  它也支持 `function`.

```
rowClassName?: string | ((rowData: Row, rowIndex: number) => string);
```

然后写一个自定义的样式，假如你为行添加的 className 为 `row-hover`.

```css
.row-hover:hover .rs-table-cell {
    background: red;
}
```
